apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontendapp
    tier: frontend
  name: frontendapp
  namespace: afnapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontendapp
