apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-storage-class
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: my-nfs-server
    path: /exported/path
