apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: glusterfs-storage
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://10.1.1.1:8080"
  restuser: "admin"
  restuserkey: "admin"
  clusterid: "my-glusterfs-cluster"
