apiVersion: v1
kind: Service
metadata:
  labels:
    app: backendapp
  name: backendapp
  namespace: app
spec:
  ports:
  - name: http
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: backendapp
